basePath: /
definitions:
  mygram-api_photo_utils.ResponseMessage:
    properties:
      data:
        example: the error explained here
        type: string
      status:
        example: fail
        type: string
    type: object
  mygram-api_user_utils.ResponseMessage:
    properties:
      data:
        example: the error explained here
        type: string
      status:
        example: fail
        type: string
    type: object
  utils.AddPhoto:
    properties:
      caption:
        example: A caption
        type: string
      photo_url:
        example: https://www.example.com/image.jpg
        type: string
      title:
        example: A Title
        type: string
    type: object
  utils.AddedPhoto:
    properties:
      caption:
        type: string
      created_at:
        type: string
      id:
        type: string
      photo_url:
        type: string
      title:
        type: string
      user_id:
        type: string
    type: object
  utils.FetchedPhoto:
    properties:
      caption:
        type: string
      created_at:
        type: string
      id:
        type: string
      photo_url:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/utils.User'
      user_id:
        type: string
    type: object
  utils.LoggedinUser:
    properties:
      token:
        example: the token generated here
        type: string
    type: object
  utils.LoginUser:
    properties:
      email:
        example: johndoe@example.com
        type: string
      password:
        example: secret
        type: string
    type: object
  utils.RegisterUser:
    properties:
      age:
        example: 8
        type: integer
      email:
        example: johndoe@example.com
        type: string
      password:
        example: secret
        type: string
      username:
        example: johndoe
        type: string
    type: object
  utils.RegisteredUser:
    properties:
      age:
        example: 8
        type: integer
      email:
        example: johndoe@example.com
        type: string
      id:
        example: the user id generated here
        type: string
      username:
        example: johndoe
        type: string
    type: object
  utils.ResponseDataAddedPhoto:
    properties:
      data:
        $ref: '#/definitions/utils.AddedPhoto'
      status:
        example: success
        type: string
    type: object
  utils.ResponseDataFetchedPhoto:
    properties:
      data:
        items:
          $ref: '#/definitions/utils.FetchedPhoto'
        type: array
      status:
        example: success
        type: string
    type: object
  utils.ResponseDataLogin:
    properties:
      data:
        $ref: '#/definitions/utils.LoggedinUser'
      status:
        example: success
        type: string
    type: object
  utils.ResponseDataRegister:
    properties:
      data:
        $ref: '#/definitions/utils.RegisteredUser'
      status:
        example: success
        type: string
    type: object
  utils.ResponseDataUpdate:
    properties:
      data:
        $ref: '#/definitions/utils.UpdatedUser'
      status:
        example: success
        type: string
    type: object
  utils.ResponseDataUpdatedPhoto:
    properties:
      data:
        $ref: '#/definitions/utils.UpdatedPhoto'
      status:
        example: success
        type: string
    type: object
  utils.ResponseMessageDelete:
    properties:
      message:
        example: your account has been successfully deleted
        type: string
      status:
        example: success
        type: string
    type: object
  utils.ResponseMessageDeletedPhoto:
    properties:
      message:
        example: your photo has been successfully deleted
        type: string
      status:
        example: success
        type: string
    type: object
  utils.UpdatePhoto:
    properties:
      caption:
        example: A new caption
        type: string
      photo_url:
        example: https://www.example.com/new-image.jpg
        type: string
      title:
        example: A new title
        type: string
    type: object
  utils.UpdateUser:
    properties:
      email:
        example: newjohndoe@example.com
        type: string
      username:
        example: newjohndoe
        type: string
    type: object
  utils.UpdatedPhoto:
    properties:
      caption:
        type: string
      id:
        type: string
      photo_url:
        type: string
      title:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  utils.UpdatedUser:
    properties:
      age:
        example: 8
        type: integer
      email:
        example: newjohndoe@example.com
        type: string
      id:
        example: here is the generated user id
        type: string
      updated_at:
        example: the updated at generated here
        type: string
      username:
        example: newjohndoe
        type: string
    type: object
  utils.User:
    properties:
      email:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: musthafafaishal@gmail.com
    name: musshal
  description: MyGram is a free photo sharing app written in Go. People can share,
    view, and comment photos by everyone. Anyone can create an account by registering
    an email address and creating a username.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  title: MyGram API
  version: "1.0"
paths:
  /photos:
    get:
      consumes:
      - application/json
      description: Get all photos with authentication user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseDataFetchedPhoto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
      security:
      - Bearer: []
      summary: Fetch all photos
      tags:
      - photos
    post:
      consumes:
      - application/json
      description: Create and store a photo with authentication user
      parameters:
      - description: Add Photo
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/utils.AddPhoto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.ResponseDataAddedPhoto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
      security:
      - Bearer: []
      summary: Store a photo
      tags:
      - photos
  /photos/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a photo by id with authentication user
      parameters:
      - description: Photo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseMessageDeletedPhoto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
      security:
      - Bearer: []
      summary: Delete a photo
      tags:
      - photos
    put:
      consumes:
      - application/json
      description: Update a photo by id with authentication user
      parameters:
      - description: Photo ID
        in: path
        name: id
        required: true
        type: string
      - description: Photo
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/utils.UpdatePhoto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseDataUpdatedPhoto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/mygram-api_photo_utils.ResponseMessage'
      security:
      - Bearer: []
      summary: Update a photo
      tags:
      - photos
  /users:
    delete:
      consumes:
      - application/json
      description: Delete a user with authentication user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseMessageDelete'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
      security:
      - Bearer: []
      summary: Delete a user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update a user with authentication user
      parameters:
      - description: Update User
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/utils.UpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseDataUpdate'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
      security:
      - Bearer: []
      summary: Update a user
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: Authentication a user and retrieve a token
      parameters:
      - description: Login User
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/utils.LoginUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseDataLogin'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
      summary: Login a user
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: create and store a user
      parameters:
      - description: Register User
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/utils.RegisterUser'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.ResponseDataRegister'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/mygram-api_user_utils.ResponseMessage'
      summary: Register a user
      tags:
      - users
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
